"""Change ratio column to Integer

Revision ID: 85c0c45b2c92
Revises: f94bee973b85
Create Date: 2023-04-02 15:34:31.452639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c0c45b2c92'
down_revision = 'f94bee973b85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'ratio', existing_type=sa.Numeric(),
                    type_=sa.Integer(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'ratio', existing_type=sa.Integer(),
                    type_=sa.Numeric(), existing_nullable=False)
    # ### end Alembic commands ###
