"""add user_id to Portfolio

Revision ID: e6065ac18558
Revises: 5c0f36ab4256
Create Date: 2023-04-19 07:09:56.862954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e6065ac18558'
down_revision = '5c0f36ab4256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version')
    op.add_column('portfolios', sa.Column(
        'user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_portfolios_user_id'),
                    'portfolios', ['user_id'], unique=False)
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.drop_index('ix_tickers_ratio', table_name='tickers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Get the inspector for the current connection
    inspector = inspect(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    if not any(index['name'] == 'ix_tickers_ratio' for index in inspector.get_indexes('tickers')):
        op.create_index('ix_tickers_ratio', 'tickers', ['ratio'], unique=False)
    op.drop_constraint('tickers_portfolio_id_fkey',
                       'portfolios', type_='foreignkey')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_column('portfolios', 'user_id')
    # op.create_table('alembic_version',
    #                 sa.Column('version_num', sa.VARCHAR(length=32),
    #                           autoincrement=False, nullable=False),
    #                 sa.PrimaryKeyConstraint(
    #                     'version_num', name='alembic_version_pkc')
    #                 )
    # ### end Alembic commands ###
