"""initial

Revision ID: f94bee973b85
Revises: 
Create Date: 2023-04-01 08:18:09.068335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94bee973b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('growth', sa.REAL(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('ticker_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_master_exchange'), 'ticker_master', ['exchange'], unique=False)
    op.create_index(op.f('ix_ticker_master_id'), 'ticker_master', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_master_ticker'), 'ticker_master', ['ticker'], unique=False)
    op.create_table('ticker_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('ticker_master_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_master_id'], ['public.ticker_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_prices_date'), 'ticker_prices', ['date'], unique=False)
    op.create_index(op.f('ix_ticker_prices_id'), 'ticker_prices', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_prices_ticker'), 'ticker_prices', ['ticker'], unique=False)
    op.create_index(op.f('ix_ticker_prices_ticker_master_id'), 'ticker_prices', ['ticker_master_id'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('ratio', sa.REAL(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['public.portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_id'), 'tickers', ['id'], unique=False)
    op.create_index(op.f('ix_tickers_portfolio_id'), 'tickers', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tickers_ratio'), 'tickers', ['ratio'], unique=False)
    op.create_index(op.f('ix_tickers_ticker'), 'tickers', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_ticker'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_ratio'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_portfolio_id'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_id'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_ticker_prices_ticker_master_id'), table_name='ticker_prices')
    op.drop_index(op.f('ix_ticker_prices_ticker'), table_name='ticker_prices')
    op.drop_index(op.f('ix_ticker_prices_id'), table_name='ticker_prices')
    op.drop_index(op.f('ix_ticker_prices_date'), table_name='ticker_prices')
    op.drop_table('ticker_prices')
    op.drop_index(op.f('ix_ticker_master_ticker'), table_name='ticker_master')
    op.drop_index(op.f('ix_ticker_master_id'), table_name='ticker_master')
    op.drop_index(op.f('ix_ticker_master_exchange'), table_name='ticker_master')
    op.drop_table('ticker_master')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
